"""att de campo de checks

Revision ID: 4e6ecf312a0e
Revises: bee4278a3db6
Create Date: 2025-06-30 13:40:23.824169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6ecf312a0e'
down_revision = 'bee4278a3db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_column('check')

    # ### end Alembic commands ###
